<%@ Page Title="" Language="C#" MasterPageFile="~/StandardMaster.master" AutoEventWireup="true" CodeBehind="SeekerTermsGuide.aspx.cs" Inherits="IntelArcade.WebApp.SeekerTermsGuid" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentHead" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentBody" runat="server">
<div>
<%--<p class="headingsNew">Seeker Terms and Conditions</p>
<br />--%>
<p class="headingsNew">Terms & Conditions of Use for Seekers</p>
<p style="padding-left:10px"><a href="#general">A. General</a><ol style="padding-left:50px">
<li><a href="#website" style="text-decoration:none; color:#444444">The Website</a></li> 
<li><a href="#services" style="text-decoration:none; color:#444444">The Services</a></li>
</ol></p>
<p style="padding-left:10px"><a href="#specific">B. Specific</a><ol style="padding-left:50px"> 
<li><a href="#ROP" style="text-decoration:none; color:#444444">Rights and Obligations of Seeker</a></li>
<li><a href="#ROC" style="text-decoration:none; color:#444444">Rights and Obligations of the Company</a></li>
<li><a href="#DL" style="text-decoration:none; color:#444444">Disclaimer of Liability</a></li>
<li><a href="#LL" style="text-decoration:none; color:#444444">Limitation of Liability</a></li>
<li><a href="#Termination" style="text-decoration:none; color:#444444">Termination</a></li>
<li><a href="#DRW" style="text-decoration:none; color:#444444">Dispute Resolution between Users of the Website</a></li>
</ol>
</p>
<p style="padding-left:10px"><a href="#miscellaneous">C. Miscellaneous</a><ol style="padding-left:50px"> 
<li><a href="#EA" style="text-decoration:none; color:#444444">Entirety of Agreement</a></li>
<li><a href="#Modification" style="text-decoration:none; color:#444444">Modification</a></li>
<li><a href="#Waiver" style="text-decoration:none; color:#444444">Waiver</a></li>
<li><a href="#Notices" style="text-decoration:none; color:#444444">Notices</a></li>
<li><a href="#Severability" style="text-decoration:none; color:#444444">Severability</a></li>
<li><a href="#CL" style="text-decoration:none; color:#444444">Choice of Law</a></li>
<li><a href="#DR" style="text-decoration:none; color:#444444">Dispute Resolution</a></li>
</ol>
</p>
<br />
<p class="headingsNew">Terms & Conditions of Use for Providers</p>
<p style="padding-left:25px;color:#6F6F6F; font-size:14px; font-weight:bold;"><a name="general">A. General</a></p>
<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="website">1. The Website</a></p>
<p style="padding-left:30px; padding-right:10px;">The website <a href="http://dialabrain.com">www.<b>diala<span class="highlight2">brain</span></b>.com</a> (the “Website”), owned and operated by <b>DIALa<span class="highlight2">BRAIN</span></b> Ltd., a private limited company organized under the laws of England and Wales (the “Company ”), is a web-based forum that matches persons or entities seeking certain personal and professional services  with <i>Providers</i> of those services (the <i>“Providers”</i>). These Terms and Conditions apply to those persons or entities that register to use the Website as a <i>Seeker</i> of services (the <i>“Seekers,”</i> and each a <i>“Seeker”</i>). The Terms and Conditions governing use of the Website by <i>Providers</i> can be found <a href="../SeekerTermsGuide.aspx">here</a>. By registering for use of the Website, the <i>Seeker</i> agrees to be bound by these Terms and Conditions, as well as the Privacy Policy of the Company (the “Privacy Policy”), which is incorporated herein by reference. You will find the Privacy Policy by clicking <a href="../PrivacyGuide.aspx">here</a>. These Terms and Conditions along with the Privacy Policy constitute the “Agreement” between you, as <i>Seeker</i>, and the Company.</p><br /> 
<p style="padding-left:30px; padding-right:10px;">By registering for use of the Website, you represent that (i) you, if a physical person, have the legal capacity to enter into contract and that you are at least 18 years of age, or, (ii) if the registered user is a legal entity (or other unincorporated group of more than one person), you are legally authorized to represent such entity or group. Please read the entirety of these Terms and Conditions before registering for use of the Website, as use of the Website constitutes a binding agreement between you and the Company. The Company reserves the right to modify these Terms & Conditions without prior notice. Any modifications will be posted on the Website before they come into effect. You are encouraged to read the Terms & Conditions on a regular basis to ensure that you are aware of any modifications. The version of these Terms & Conditions in force at any given date will govern the relationship between you and the Company. If for any reason you do not wish to be bound by or cannot comply with these Terms and Conditions, please do not register for use of the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">The Website is owned and operated by the Company. All intellectual property used on the Website is either owned by the Company or an affiliate of the Company, or is licensed from third parties pursuant to a valid license agreement. The Company makes no representation or warranty that the Website will function as intended without interruption or error, and the Company hereby disclaims any and all liability in this respect. In particular, but not by way of limitation, the Company does not make any representations or warranties regarding the proper functioning of any third-party software or platform that the Company uses or relies upon to ensure the full functionalities of the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">As a matter of policy, the Website does not accept the offer or provision of the following services: gaming, gambling, or betting (upon payment or without payment), card-reading, Tarot, or other forms of fortune-telling or acting as a so-called “medium” or the equivalent, or religious or other denominational services. The Company will decide at its own discretion whether any of the foregoing or similar services are being offered and reserves the right to delete any such services at any time. If you, as a user, notice that any of the foregoing services are being offered on the Website, please notify the Company at your earliest convenience at <a href="mailto:admin@dialabrain.com">admin@dialabrain.com.</a></p><br />

<p style="padding-left:25px;font-size:13px; font-weight:bold"><a name="services">2. The Services</a></p>
<p style="padding-left:30px; padding-right:10px;">
<b>DIALa<span class="highlight2">BRAIN</span></b> is designed to allow <i>Providers</i> of a variety and range of personal and professional services (including related products) to meet the needs of <i>Seekers</i> of such services and to create a marketplace for <i>Seekers</i> and <i>Providers</i> to come together during a pre-booked “session” (“Session”) through the use of the Website and its video-conferencing facilities (collectively, the “Services”). To register for use of the Website, you must comply with provided requests for information, including, inter alia., full name of person (on his or her own behalf or on behalf of an unincorporated group of persons) or entity, address, and email, and, if a legal entity, the legal entity’s or company name and identification number, VAT number, if applicable, and authorised signatories. In addition, all <i>Providers</i> will need to provide details of the PayPal account into which the Company can make relevant payments according to these Terms & Conditions. (Click here to establish a PayPal account.) The Company shall use the email address provided by the <i>Provider</i> as such <i>Provider</i>’s unique identifier. You will also need a password of your own choosing. Our obligation to verify the identity and other details of registered users is limited to those set forth hereafter in Rights and Obligations of the Company. </p><br />
<p style="padding-left:30px; padding-right:10px;">
The Company does not verify the credentials and qualifications of the Providers and has no obligation to do so beyond those obligations set forth hereafter in Rights and Obligations of the Company. The Company makes no representation or warranty that a <i>Provider</i> is willing and/or able to provide services meeting the expectations of the <i>Seeker</i> or that a <i>Provider</i> is qualified for the particular category for which it is registered on the Website. It is the <i>Seeker</i>'s obligation to independently verify that the <i>Provider</i> is competent to render the services such <i>Provider</i> purports to be competent to provide. The Company encourages <i>Seekers</i> to particularly scrutinize the services offered by <i>Providers</i> rendering services in respect of any professions, such as medical doctors, dentists, mental health professionals, lawyers, accountants, etc., to ensure that such <i>Providers</i> possess the relevant qualifications necessary to meet the needs of the <i>Seeker</i>. Towards this end, all <i>Providers</i> are requested to complete the relevant form regarding the <i>Provider</i>’s profile upon registration on the Website. In that form, each <i>Provider</i> is requested to provide relevant details of the <i>Provider</i>’s educational and professional qualifications. It is in the <i>Provider</i>’s interest to ensure that these details are accurate and up-to-date. See form <a href="../ProviderSetup/CompanyDisplay.aspx">here</a>.</p><br />
<p style="padding-left:30px; padding-right:10px;">
THE COMPANY DOES NOT ENDORSE, RECOMMEND, VERIFY, EVALUATE OR GUARANTEE ANY SERVICES RENDERED BY <i>PROVIDERS</i> VIA THE WEBSITE, AND NEITHER THE COMPANY, ITS AFFILIATES, SHAREHOLDERS, DIRECTORS, EMPLOYEES, NOR AGENTS WILL BE LIABLE FOR ANY DAMAGES INCURRED BY A <i>SEEKER</i> OWING TO SUCH <i>SEEKER</i>'S RELIANCE ON ANY SUCH SERVICES RENDERED BY A <i>PROVIDER</i>, AND THE <i>PROVIDER</i> SHALL HOLD THE COMPANY HARMLESS FOR ANY DAMAGES SOUGHT BY A <i>SEEKER</i> IN RESPECT OF <i>PROVIDER</i>'S SERVICES. THE CONTRACTUAL RELATIONSHIP REMAINS BETWEEN <i>PROVIDER</i> AND <i>SEEKER</i>, AND THE COMPANY DOES NOT ACT, NOR SHOULD IT BE DEEMED TO BE ACTING, AS AN AGENT OF EITHER <i>PROVIDER</i> OR <i>SEEKER</i>.</p><br /> 
<p style="padding-left:30px; padding-right:10px;">
<i>Providers</i> hereby release and agree to hold harmless the Company, its affiliates, shareholders, directors, officers, employees, agents, successors, advisers, consultants, and assigns from any and all causes of action and claims of any nature resulting from the acts of any <i>Seekers</i> contacted or with whom they otherwise come into contact via the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">
The Company shall verify that a relevant <i>Seeker</i> has purchased via the Website the necessary credits to cover the payment of the Services for the relevant Session booked with the <i>Provider</i>. If the transaction is cross-border, the exchange rate that the Company will use is the relevant rate on the date that the <i>Seeker</i> requests a Session regardless of the date such requested Session is accepted by the <i>Provider</i>. After the relevant Session has ended, the Company will make the relevant payment to the <i>Provider</i>, unless there is a dispute in respect of the services provided; provided, however, that no fees are payable if the Session lasts less than 90 seconds, as determined by <b>DIALa<span class="highlight2">BRAIN</span></b>’s webserver UTC clock. In this case, please see item 6 (Dispute Resolution between Users of the Website) below. If the booked Session is cancelled by the Seeker within 12 hours of the scheduled time, 5% of the relevant payment will be paid to the <i>Provider</i>. If the <i>Seeker</i> does not appear for the Session, then 5% of the relevant payment will be paid to the <i>Provider</i> (“No-Show Fee”), provided that the <i>Provider</i> had entered the Session and waited at least 10 minutes beyond the scheduled Session time. However, it the Session was scheduled for less than 10 minutes, and the <i>Provider</i> is available for the entire scheduled period, then the <i>Provider</i> is entitled to his or her fee for such period. (Please note that these fees are not cumulative.) If the <i>Seeker</i> enters the Session after more than 10 minutes and the <i>Provider</i> is still in the Session, then the Session is deemed to commence when the latter of the <i>Provider</i> and the <i>Seeker</i> entered the Session, and the No-Show Fee is not applicable. The Company has no other obligation beyond those obligations set forth hereafter in Rights and Obligations of the Company. The Company makes no representation or warranty that a given <i>Seeker</i> is willing and/or able to pay for the Services rendered by a <i>Provider</i> prior to the actual booking of a Session. </p><br />
<p style="padding-left:30px; padding-right:10px;">
The Website also enables user feedback as well as a recommendation system whereby <i>Seekers</i> may recommend <i>Providers</i> based on their experience with such <i>Providers</i> via the Website. <i>Providers</i> hereby release and agree to hold harmless the Company, its affiliates, shareholders, directors, officers, employees, agents, successors, advisers, consultants, and assigns from any and all causes of action and claims of any nature, including, but not limited to defamation, resulting from the acts of any <i>Seekers</i> in respect of the user feedback and/or recommendation system enabled by the Website.
</p>
<br />

<p style="padding-left:25px;color:#6F6F6F; font-size:14px; font-weight:bold;"><a name="specific">B. Specific</a></p>
<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="ROP">1. Rights and Obligations of Seeker</a></p>
<p style="padding-left:30px; padding-right:10px;">Subject to your compliance with these Terms & Conditions, as may be modified from time to time, you have the right, as a registered user, to access the Website, view the information provided thereon, and otherwise use the Services as intended by the Company. Your right to do the foregoing is non-exclusive, limited, revocable, subject to termination by the Company as set forth herein, and cannot be assigned, sub-licensed, or otherwise transferred.</p> <br />
<p style="padding-left:30px; padding-right:10px;">As a registered user of the Website, you must comply with these Terms and Conditions, as may be modified from time to time, as well as applicable law. If you choose to submit information to the Company, you thereby represent and warrant that such information is accurate, and that the submission of such information does not infringe on the rights of any third party. You also have the obligation to keep such information updated at all times to ensure its accuracy. If you believe at any time that any other person or entity is using your identity in a way that you have not authorized, you must immediately inform the Company of such unauthorized use as provided herein. You have the obligation to maintain the security of your password, as chosen by you, and you remain liable for your account activity until you have notified the Company of misuse and have received written confirmation from the Company (by email or otherwise) that it has received such notice.</p><br /> 
<p style="padding-left:30px; padding-right:10px;">If you choose to use the Services, you have the obligation to transact the services that you have sought with a <i>Provider</i> identified on the Website via the Website and to accept to pay for such services directly via the Company, including all applicable taxes. </p><br />
<p style="padding-left:30px; padding-right:10px;">The Company acts solely as intermediary in respect of payments, and, therefore, you agree that the Company may deduct and withhold via the Website the relevant amount for the services purchased by you. Services are billed based on the price provided by the <i>Provider</i> and the time spent interacting with the <i>Seeker</i>, based on increments of one (1) minute. Please note that in respect of any Session it is the time tabulated by <b>DIALa<span class="highlight2">BRAIN</span></b>’s webserver UTC clock that determines the billable amount of time spent during a Session, and which, in turn, is used to establish the relevant invoice. A Session formally begins only when both the <i>Seeker</i> and the <i>Provider</i> are in the Session according to our server logs, and such Session formally ends when either the <i>Seeker</i> or Provide exits from such Session based on our server logs. You agree to abide by the time for a Session as determined by <b>DIALa<span class="highlight2">BRAIN</span></b>’s webserver UTC clock. Furthermore, you, as <i>Seeker</i>, agree not to pay a Provider directly for the services provided. Subject to the Company’s involvement, at its sole discretion, in disputes between <i>Seekers</i> and <i>Providers</i>, as further described in these Terms & Conditions, you agree to absolve the Company of any responsibility and liability in respect of disputes with any <i>Provider</i>.</p><br />
<p style="padding-left:30px; padding-right:10px;">If you choose to provide any user-generated content on the Website, you thereby grant the Company a non-exclusive, limited, and worldwide license to distribute and publish such content on the Website. You may withdraw such content at any time upon notice to the Company. The Company will take down any such content within a reasonable period of time, and, in any event, within 30 days of receipt of such notice of withdrawal. You are encouraged to read our Privacy Policy before submitting any information or registering for use of the Website, as the Privacy Policy constitutes part of this Agreement.</p><br />
<p style="padding-left:30px; padding-right:10px;">You have the obligation to indemnify and hold the Company harmless from any damages, losses, and costs, including, but not limited to, reasonable attorneys' fees, incurred relating to third-party claims as a result of your breach of these Terms and Conditions, your submission of content to the Website, or any other actions or omissions in respect of the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">If you believe that, for any reason, you may or must act in a way that is contrary to these Terms and Conditions, you are obligated to provide the Company with prior written notice and the details thereof, and you agree to allow the Company adequate time to propose an alternative remedy that complies with applicable law in such instance.</p><br />


<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="ROC">2. Rights and Obligations of the Company</a></p>
<p style="padding-left:30px; padding-right:10px;">Through the Website, the Company seeks to match <i>Seekers</i> and <i>Providers</i> of personal and professional services. When a <i>Seeker</i> or <i>Provider</i> registers for use of the Website, such person or entity is required to provide certain requested information about such person or entity. The Company makes no independent verification of the accuracy or reliability of such information other than to review whether the information is internally consistent with the other data provided by such <i>Seeker</i> or <i>Provider</i>. You are solely responsible for your interactions with other users of the Website. The Company may also limit or forbid your use of the Website and the Services, and may limit or prohibit your contacting other users of the Website. The Company may, at its sole discretion, monitor disputes between users of the Website, and, more specifically, between <i>Seekers</i> and <i>Providers</i>, but has no obligation to do so. </p><br />
<p style="padding-left:30px; padding-right:10px;">The Company may update, change, or discontinue the Website at any time and at its sole discretion. Any such update, change, or discontinuance shall be effective upon its posting on the Website or being otherwise communicated. The Company permits you to access and use the Website at any given time as it exists at such time, and has no other obligations other than those provided in these Terms and Conditions. </p><br />
<p style="padding-left:30px; padding-right:10px;">All rights not expressly granted in these Terms and Conditions are reserved to the Company, including, but not limited to, intellectual property and other rights and interest in the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">The Company reserves the right to refuse, discard or remove any user-generated content or any other content or information provided by the user of the Website without notice to such user. The Company has no obligation to store, maintain or provide copies of any content or information provided by the <i>Seeker</i> when using the Services.</p><br />
<p style="padding-left:30px; padding-right:10px;">The Website may include links to third-party websites that are made available from time to time on the Website. The Company does not endorse, recommend, or evaluate products or materials made available through such websites, and is not liable for the use thereof by users of the Website. If you leave the Website by accessing such third-party website, you do so at your own risk, and these Terms and Conditions do not apply to such third-party websites.</p><br />
<p style="padding-left:30px; padding-right:10px;">The Company may send information and notices regarding the Website and the Services to you via the email address that you provide and via other means. You acknowledge and agree that the Company has no liability in respect of record-keeping or the failure to keep accurate records, including the provision of information and notices. </p><br />
<p style="padding-left:30px; padding-right:10px;">Regardless of our Privacy Policy, the Company may access and disclose the information that you provide to the Company if requested to do so by law or if such action is reasonably necessary to comply with legal process, deal with third-party claims, protect the rights of the Company, other users of the Website, or the public at large, and to enforce these Terms and Conditions.</p><br />


<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="DL">3. Disclaimer of Liability</a></p>
<p style="padding-left:30px; padding-right:10px;">AS CERTAIN COUNTRIES DO NOT PERMIT THE EXCLUSION OF LIABILITY IN CONSUMER AGREEMENTS, THE FOLLOWING MAY NOT BE APPLICABLE IN YOUR CASE.</p><br />
<p style="padding-left:30px; padding-right:10px;">THE WEBSITE AND THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE”. TO THE FULLEST EXTENT UNDER APPLICABLE LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, SECURITY OR ACCURACY. THE COMPANY FURTHERMORE EXPRESSLY DISCLAIMS ALL WARRANTIES FOR INFORMATION POSTED OR TRANSMITTED BY <i>PROVIDERS</i>. IF A <i>SEEKER</i> CHOOSES TO RELY ON INFORMATION PROVIDED BY A <i>PROVIDER</i>, THE <i>SEEKER</i> DOES SO AT ITS OWN RISK. THE <i>SEEKER</i> SHALL NOT HAVE ANY CLAIM AGAINST THE COMPANY, ITS AFFILIATES, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS OR AGENTS IN RESPECT OF THE SERVICES RENDERED. IF A <i>SEEKER</i> CHOOSES TO PURCHASE THE SERVICES OF A <i>PROVIDER</i>, SUCH PURCHASE OF SERVICES IS AT SUCH <i>SEEKER</i>'S OWN RISK.</p><br />
<p style="padding-left:30px; padding-right:10px;">NEITHER THE COMPANY, ITS AFFILIATES, NOR THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS ARE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES (INCLUDING, BUT NOT LIMITED TO, LOSS OF BUSINESS REVENUE) ARISING FROM THE SERVICES OR ANY PROVISION OF THIS AGREEMENT. </p><br />
<p style="padding-left:30px; padding-right:10px;">THE COMPANY IS NOT LIABLE FOR ENFORCING ANY AGREEMENT THAT WAS MADE BETWEEN A <i>SEEKER</i> AND A <i>PROVIDER</i> IN ANY RESPECT. USERS OF THE WEBSITE AND SERVICES ARE SOLELY RESPONSIBLE FOR ANY AGREEMENT MADE BETWEEN THEM. IN THE EVENT OF A DISPUTE REGARDING ANY TRANSACTION CONDUCTED THROUGH THE WEBSITE, THE USERS OF THE WEBSITE HEREBY RELIEVE THE COMPANY, ITS AFFILIATES, THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS FROM ALL CLAIMS, ANY AND ALL LOSSES (DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL), DAMAGES, COSTS AND EXPENSES, INCLUDING, WITHOUT LIMITATION, COURT COSTS AND ATTORNEYS' FEES, WHICH A USER MAY HAVE AGAINST ONE OR MORE OF THE ABOVE.</p><br />


<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="LL">4. Limitation of Liability</a></p>
<p style="padding-left:30px; padding-right:10px;">AS CERTAIN COUNTRIES DO NOT PERMIT THE LIMITATION OF LIABILITY IN CONSUMER AGREEMENTS, THE FOLLOWING MAY NOT BE APPLICABLE IN YOUR CASE.</p><br />
<p style="padding-left:30px; padding-right:10px;">THE COMPANY, ITS AFFILIATES, THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS’ AGGREGATE LIABILITY FOR DIRECT OR INDIRECT DAMAGES ARISING UNDER THIS AGREEMENT SHALL NOT UNDER ANY CIRCUMSTANCES EXCEED THE TOTAL AMOUNT PAID BY ANY <i>SEEKER</i> TO ANY AND ALL <i>PROVIDERS</i> THROUGH THE WEBSITE IN THE 30 DAYS PRIOR TO THE NOTICE TO THE COMPANY OF THE CLAIM. </p><br />


<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="Termination">5. Termination</a></p>
<p style="padding-left:30px; padding-right:10px;">The Company may terminate this Agreement at any time without cause, and with or without notice. You, as <i>Seeker</i>, may terminate this Agreement with the Company at any time without cause, upon providing notice to the Company of such termination. Upon termination of this Agreement, you shall no longer have access to the Website or the Services. Notwithstanding the foregoing, the Company reserves the right to suspend activity of a user account without terminating this Agreement if there is an outstanding dispute between a <i>Seeker</i> and <i>Provider</i> regarding the provision of services. Such account may be terminated by the Company upon resolution of such dispute.</p><br />


<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="DRW">6. Dispute Resolution between Users of the Website</a></p>
<p style="padding-left:30px; padding-right:10px;">By agreeing to the Terms & Conditions, you are agreeing to abide by the dispute resolution procedures between users as hereinafter set forth. <b>DIALa<span class="highlight2">BRAIN</span></b> encourages users to resolve any disputes arising in connection with the use of the Website between themselves. <b>DIALa<span class="highlight2">BRAIN</span></b>, may, however, without any legal obligation to do so, facilitate the resolution of the any dispute between users arising in connection with the use of the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">In the event that a user has a dispute in respect of the use of the Website with another user, whether, for example, it is a <i>Seeker</i> disputing delivery of services by a <i>Provider</i> or a <i>Provider</i> contesting negative feedback or otherwise (each a “Dispute”), then such user (“Initiator”) shall notify in writing both the other user (“Informee”) as well as <b>DIALa<span class="highlight2">BRAIN</span></b> of the nature of such dispute and the remedy the Initiator is seeking (“Notification”). </p><br />
<p style="padding-left:30px; padding-right:10px;">If <b>DIALa<span class="highlight2">BRAIN</span></b> chooses to facilitate the dispute resolution and the remedy demanded by the Initiator is less than the equivalent of 1000 euros, then the dispute resolution process shall proceed as follows: </p><br />
<p style="padding-left:30px; padding-right:10px;">Within 10 calendar days of receipt of the Notification, <b>DIALa<span class="highlight2">BRAIN</span></b> shall request the Informee to submit a written response to the Notification (“Response”), which Response shall be submitted to the Initiator and <b>DIALa<span class="highlight2">BRAIN</span></b> within 10 calendar days of the receipt of <b>DIALa<span class="highlight2">BRAIN</span></b>’s request. Within 10 calendar days of the receipt of the Response by <b>DIALa<span class="highlight2">BRAIN</span></b>, <b>DIALa<span class="highlight2">BRAIN</span></b> shall arrange a conference call, via either our web-based video-conferencing or telephone, with the Initiator and Informee. Upon agreement of all parties, the Company may record these discussions. The conference call shall be limited to a maximum period of 30 minutes. Within 5 calendar days of the conference call, <b>DIALa<span class="highlight2">BRAIN</span></b> shall render its decision on the Dispute (“Decision”), and act accordingly. The Initiator and Informee shall respect the decision of <b>DIALa<span class="highlight2">BRAIN</span></b> without further recourse. The Company reserves the right to outsource dispute resolution to a third party. All communications, including the Notification, Response, and Decision shall be via email to the relevant email address posted on the Website.</p><br />
<p style="padding-left:30px; padding-right:10px;">In lieu of or in addition to the foregoing, if the remedy demanded by the Initiator is the equivalent of 1000 euros or more, then, unless otherwise mutually agreed by the Initiator and the Informee, <b>DIALa<span class="highlight2">BRAIN</span></b> may, at its sole discretion, arrange for an independent third-party alternative dispute resolution <i>Provider</i> (“ADR <i>Provider</i>”) to assist with the resolution of the Dispute. Such alternative dispute resolution process shall be determined by the ADR <i>Provider</i>, provided that the alternative dispute resolution proceedings (i) are conducted online, by telephone, or solely based on written submissions; (ii) shall not involve any personal appearance by the Initiator, Informee, or witnesses unless otherwise mutually agreed by the Initiator and Informee; (iii) are accepted as binding on the Initiator and Informee, and provided further that (iv) any judgment on the award rendered by the ADR <i>Provider</i> may be entered in any court of competent jurisdiction. The costs of such alternative dispute resolution shall be borne by the Initiator or Informee, or both, as determined by the ADR <i>Provider</i>. You hereby agree to submit to the proceedings of and accept any decision rendered by such ADR <i>Provider</i>.</p><br />


<p style="padding-left:25px;color:#6F6F6F; font-size:14px; font-weight:bold;"><a name="miscellaneous">C. Miscellaneous</a></p>
<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="EA">1. Entirety of the Agreement</a></p>
<p style="padding-left:30px; padding-right:10px;">This Agreement, together with any documents referred to herein, or expressed to be entered into in connection with it, constitutes the entire agreement between the Company and you, as <i>Seeker</i>, concerning the subject matter thereof, and supersedes all prior agreements or understandings.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="Modification">2. Modification</a></p>
<p style="padding-left:30px; padding-right:10px;">The Company may at its sole discretion modify the terms of this Agreement at any time, which modifications shall be effective upon posting on the Website or notification through other means of communication. If you choose not to agree to any such modifications, your sole recourse is to terminate the Agreement with the Company and cease use of the Website and the use of the Services.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="Waiver">3. Waiver</a></p>
<p style="padding-left:30px; padding-right:10px;">No failure or delay on the part of the Company to exercise any right hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right hereunder by the Company preclude any further exercise thereof or the exercise of any other right.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="Notices">4. Notices</a></p>
<p style="padding-left:30px; padding-right:10px;">The Company may notify you via posting on the Website, via email or via other means of communication. You may notify the Company via courier to the following Company address or the following email address: <a href="mailto:support@dialabrain.com">support@dialabrain.com</a>. The Company has no obligation to respond to any notice received.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="Severability">5. Severability</a></p>
<p style="padding-left:30px; padding-right:10px;">In the event that any of the provisions of this Agreement are held to be invalid or unenforceable by judicial decision or arbitration award, the remaining provisions hereof shall remain in full effect, and the provisions held or declared invalid or unenforceable shall, wherever feasible, be automatically deemed amended to the extent necessary to permit such provision to avoid such invalidity or unenforceability.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="CL">6. Choice of Law</a></p>
<p style="padding-left:30px; padding-right:10px;">This Agreement shall be subject to and interpreted in accordance with the laws of England and Wales.</p><br />

<p style="padding-left:25px; font-size:13px; font-weight:bold"><a name="DR">7. Dispute Resolution</a></p>
<p style="padding-left:30px; padding-right:10px;">Any disputes arising out of the performance or the interpretation of this Agreement and that cannot be resolved amicably  shall be settled by mediation in accordance with the Centre for Effective Dispute Resolution (“CEDR”) Model Mediation Procedure to be held in English in London, England. The mediator will be nominated be <a href="http://cedr.com">CEDR</a>. </p><br />
<p style="text-align:center; font-weight:bold">END OF TERMS AND CONDITIONS OF USE FOR SEEKERS</p>

<br />
</div>
<p class="headingsNew"><a name="Guidance" style="color:White; text-decoration:none;">Guidance</a></p>
		<div class="contentBody_leftSide" style="padding-left:10px">
            <b><img src="/images/arrow.gif" alt=">" /> <span class="title"  style="text-decoration:none; color:#414141; cursor:default">Frequently Asked Questions</span></b><br />
            <ul style="padding-left:30px">
			<li><a href="UsageFAQ.aspx">Using this site</a></li><li><a href="ProviderFAQ.aspx">Service Providers</a></li><li><a href="SeekerFAQ.aspx">Service Seekers</a></li><li><a href="BillingFAQ.aspx">Billing and Payments</a></li><li><a href="DIALaBRAINFAQ.aspx" >What is <span style="color:#414141; font-weight:bold">DIALa<span class="highlight2">BRAIN</span></span>?</a></li></ul><br/>
            
			<b><img src="/images/arrow.gif" alt=">" /> <span class="title"  style="text-decoration:none; color:#414141; cursor:default">Guides for Seekers and Providers</span></b><br />
			<ul style="padding-left:30px"><li><a href="PrePayGuide.aspx"><span style="color:#414141; font-weight:bold">d<span class="highlight2">b</span></span>-<i>Time</i> and PrePay</a></li><li><a href="InvoiceGuide.aspx">Making and receiving Payments</a></li><li><a href="FeedbackGuide.aspx">Recommendations and Feedback</a></li><li><a href="RegistrationGuide.aspx">Registering with <span style="color:#414141; font-weight:bold">DIALa<span class="highlight2">BRAIN</span></span></a></li></ul><br/>
			<b><img src="/images/arrow.gif" alt=">" /> <span class="title"  style="text-decoration:none; color:#414141; cursor:default">Service Seeker Guides</span></b><br />
			<ul style="padding-left:30px"><li><a href="TrustGuide.aspx">Building trust</a></li><li><a href="SelectionGuide.aspx">Selecting a Provider and Having a Meeting</a></li></ul>

		</div>
		<div class="contentBody_rightSide">
			<b><img src="/images/arrow.gif" alt=">" /> <span class="title"  style="text-decoration:none; color:#414141; cursor:default">Service Provider and Company Guides</span></b><br />
			<ul style="padding-left:30px"><li><a href="P_BenenfitsGuide.aspx">The benefits for Providers</a></li><li><a href="ConferencingGuide.aspx">Web conferencing tools</a></li><li><a href="ProviderGuide.aspx">Becoming a service Provider</a></li><li><a href="ReferredGuide.aspx">How to pay almost no commission</a></li><li><a href="ProfileGuide.aspx">Writing a profile</a></li><li><a href="PhotographGuide.aspx">Photos and creating the right image</a></li><li><a href="MarketGuide.aspx">How to market yourself</a></li><li><a href="FeesGuide.aspx">What are my costs as a Provider</a></li></ul><br/>
			<b><img src="/images/arrow.gif" alt=">" /> <span class="title"  style="text-decoration:none; color:#414141; cursor:default"><span style="color:#414141; font-weight:bold">DIALa<span class="highlight2">BRAIN</span></span> &amp; Policies </span></b><br />
			<ul style="padding-left:30px"><li><a href="OverviewGuide.aspx">An overview of <span style="color:#414141; font-weight:bold">DIALa<span class="highlight2">BRAIN</span></span></a></li><li><a href="PrivacyGuide.aspx">Privacy Policy</a></li><li><a href="SeekerTermsGuide.aspx">Seeker Terms and Conditions</a></li><li><a href="ProviderTermsGuide.aspx">Provider Terms and Conditions</a></li><li><a href="ContactUsGuide.aspx">Contact Us</a></li></ul>
		</div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentRightAbove" runat="server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentRightBelow" runat="server">
</asp:Content>
